config/routes.rb
Rails.application.routes.draw do
  get "/tasks", to: "tasks#index", as: :tasks
  get "/tasks/new", to: "tasks#new", as: :new_task
  get "/tasks/:id", to: "tasks#show", as: :task
  post "/tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end


#verb "/somewhere", to: "controllerS#action", alis

  # #Read
  # #Read all
  # get "/restaurants", to: "restaurants#index", as: "restaurants"
  # #Read one
  # get "/restaurants/:id", to: "restaurants#show", as: "restaurant"
  # #Create
  # get "/restaurants/new", to: "restaurants#new", as: "new_restaurant"
  # post "/restaurants", to: "restaurants#create"
  # #Update
  # get "/restaurants/:id/edit", to: "restaurants#edit", as: "edit_restaurant"
  # patch "/restaurants/:id", to: "restaurants#update"
  # #Delete
  # delete "restaurants/:id", to: "restaurants#destroy"

# First, add a new route to list the tasks, following the convention from the lecture.
# Then, add a controller action and its view. This action should fetch all tasks,
# and a view should loop over these to display them, like in the screenshot below.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |f| %>
  <%= f.label :title, "Insert the title" %>
  <%= f.text_field :title  %>
  <%= f.label :details, "Insert the details" %>
  <%= f.text_field :details  %>
  <%= f.label :completed, "Insert the completed" %>
  <%= f.check_box :completed  %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<h1>edit here</h1>
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks!</h1>
<!-- pe -->
<% @tasks.each do |task| %>
  <p><%= check_box("tag", tag.id, {checked: task.completed}) %>
    <%= link_to task.title, task_path(task) %></p>
  <hr>
<% end %>

<%= link_to "Create a new task", new_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1><%= @task.title %><%= check_box("tag", tag.id, {checked: @task.completed}) %></h1>
<p>Details: <%= @task.details %></p>
<hr>

<%= link_to "Back to all tasks", tasks_path %>
<%= link_to "Edit task", edit_task_path %>
<%= link_to "Delete task", task_path(@task), method: :delete %>